from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.append(str(PROJECT_ROOT))


from app.services.weather_service import WeatherService
from app.services.drift_engine import DriftEngine

from scripts.synthetic.generate_synthetic_ais import (
    generate_scenario_dataset,
)

from scripts.synthetic.scenario import (
    SyntheticScenarioConfig,
)


OUTPUT_DIR = (
    PROJECT_ROOT
    / "data"
    / "ais"
    / "processed"
)


# ================================================================
# TRUE SOURCE
# ================================================================

TRUE_SOURCE_LATITUDE = 34.80
TRUE_SOURCE_LONGITUDE = 24.00

RELEASE_TIME = datetime(
    2019,
    10,
    15,
    12,
    0,
    0,
    tzinfo=timezone.utc,
)

DRIFT_DURATION_HOURS = 6.0
TIMESTEP_MINUTES = 15

WINDAGE = 0.03


def main() -> None:

    print("=" * 80)
    print("SCENARIO-005 GENERATION")
    print("=" * 80)

    # ============================================================
    # 1. TRUE RELEASE
    # ============================================================

    print()
    print("TRUE OIL RELEASE")
    print("-" * 80)

    print(
        f"Latitude       : "
        f"{TRUE_SOURCE_LATITUDE:.6f}"
    )

    print(
        f"Longitude      : "
        f"{TRUE_SOURCE_LONGITUDE:.6f}"
    )

    print(
        f"Release time   : "
        f"{RELEASE_TIME.isoformat()}"
    )

    print(
        f"Drift duration : "
        f"{DRIFT_DURATION_HOURS} hours"
    )

    print(
        f"Timestep       : "
        f"{TIMESTEP_MINUTES} minutes"
    )

    print(
        f"Windage        : "
        f"{WINDAGE}"
    )

    # ============================================================
    # 2. ENVIRONMENTAL DATA
    # ============================================================

    weather_yearly_dir = (
        PROJECT_ROOT
        / "data"
        / "weather"
        / "raw"
        / "yearly"
    )

    ocean_yearly_dir = (
        PROJECT_ROOT
        / "data"
        / "ocean"
        / "raw"
        / "yearly"
    )

    print()
    print("ENVIRONMENTAL DATA")
    print("-" * 80)

    print(f"Weather directory : {weather_yearly_dir}")
    print(f"Ocean directory   : {ocean_yearly_dir}")

    if not weather_yearly_dir.exists():
        raise FileNotFoundError(
            "Weather yearly directory does not exist:\n"
            f"{weather_yearly_dir}"
        )

    if not ocean_yearly_dir.exists():
        raise FileNotFoundError(
            "Ocean yearly directory does not exist:\n"
            f"{ocean_yearly_dir}"
        )

    # ============================================================
    # 3. WEATHER SERVICE
    # ============================================================

    weather_service = WeatherService(
        weather_yearly_dir=weather_yearly_dir,
        ocean_yearly_dir=ocean_yearly_dir,
    )

    # ============================================================
    # 4. DRIFT ENGINE
    # ============================================================

    drift_engine = DriftEngine(
        weather_service=weather_service,
        windage=WINDAGE,
    )

    # ============================================================
    # 5. GENERATE REALISTIC SAR OBSERVATION
    #
    # IMPORTANT:
    # The observation is NOT manually chosen.
    #
    # It is generated by exactly the same DriftEngine that is
    # later used by the hindcast service.
    # ============================================================

    print()
    print("=" * 80)
    print("FORWARD DRIFT SIMULATION")
    print("=" * 80)

    print()
    print("Running:")
    print("  DriftEngine.forward_drift()")

    trajectory = drift_engine.forward_drift(
        start_latitude=TRUE_SOURCE_LATITUDE,
        start_longitude=TRUE_SOURCE_LONGITUDE,
        start_time=RELEASE_TIME,
        duration_hours=DRIFT_DURATION_HOURS,
        timestep_minutes=TIMESTEP_MINUTES,
    )

    if trajectory is None:
        raise RuntimeError(
            "DriftEngine.forward_drift() returned None."
        )

    # ============================================================
    # 6. VALIDATE TRAJECTORY
    # ============================================================

    if not trajectory.states:
        raise RuntimeError(
            "Forward drift returned an empty trajectory."
        )

    print()
    print(
        f"Trajectory states generated: "
        f"{len(trajectory.states)}"
    )

    # ============================================================
    # 7. FINAL STATE = SYNTHETIC SAR OBSERVATION
    # ============================================================

    final_state = trajectory.states[-1]

    observation_lat = float(
        final_state.latitude
    )

    observation_lon = float(
        final_state.longitude
    )

    observation_time = final_state.timestamp

    # Ensure UTC timezone
    if observation_time.tzinfo is None:
        observation_time = observation_time.replace(
            tzinfo=timezone.utc
        )
    else:
        observation_time = observation_time.astimezone(
            timezone.utc
        )

    print()
    print("GENERATED OBSERVATION")
    print("-" * 80)

    print(
        f"Observation latitude  : "
        f"{observation_lat:.8f}"
    )

    print(
        f"Observation longitude : "
        f"{observation_lon:.8f}"
    )

    print(
        f"Observation time      : "
        f"{observation_time.isoformat()}"
    )

    print()

    # ============================================================
    # 8. SANITY CHECK
    # ============================================================

    actual_duration_hours = (
        observation_time - RELEASE_TIME
    ).total_seconds() / 3600.0

    print(
        f"Actual simulated duration: "
        f"{actual_duration_hours:.4f} hours"
    )

    if abs(
        actual_duration_hours
        - DRIFT_DURATION_HOURS
    ) > 1e-6:

        raise RuntimeError(
            "Forward drift ended at an unexpected time.\n"
            f"Expected duration: {DRIFT_DURATION_HOURS} hours\n"
            f"Actual duration:   {actual_duration_hours} hours"
        )

    # ============================================================
    # 9. CREATE SCENARIO CONFIGURATION
    # ============================================================

    print()
    print("=" * 80)
    print("CREATING SCENARIO-004 AIS DATASET")
    print("=" * 80)

    config = SyntheticScenarioConfig(

        # --------------------------------------------------------
        # Scenario
        # --------------------------------------------------------

        scenario_id="scenario-005",

        # --------------------------------------------------------
        # TRUE OIL RELEASE
        # --------------------------------------------------------

        release_lat=TRUE_SOURCE_LATITUDE,
        release_lon=TRUE_SOURCE_LONGITUDE,
        release_time=RELEASE_TIME,

        # --------------------------------------------------------
        # SYNTHETIC SAR OBSERVATION
        # --------------------------------------------------------

        observation_lat=observation_lat,
        observation_lon=observation_lon,
        observation_time=observation_time,

        drift_duration_hours=DRIFT_DURATION_HOURS,

        # --------------------------------------------------------
        # AIS REGION
        #
        # Same region as Scenario-003.
        # --------------------------------------------------------

        bounds_lat_min=34.5,
        bounds_lat_max=35.5,

        bounds_lon_min=23.5,
        bounds_lon_max=24.5,

        # --------------------------------------------------------
        # FLEET
        # --------------------------------------------------------

        num_background_vessels=150,

        num_decoy_vessels=5,

        vessel_id_prefix="SYNTH-005-",

        source_vessel_id="SYNTH-005-SRC",

        decoy_start_id=1,

        # --------------------------------------------------------
        # Same five engineered decoy behaviors as Scenario-003
        # --------------------------------------------------------

        decoy_behaviors=[
            "DCY01",
            "DCY02",
            "DCY03",
            "DCY04",
            "DCY05",
        ],

        # --------------------------------------------------------
        # Oil model
        # --------------------------------------------------------

        windage=WINDAGE,

        # --------------------------------------------------------
        # Reproducibility
        # --------------------------------------------------------

        seed=43,
    )

    # ============================================================
    # 10. GENERATE AIS
    # ============================================================

    print()
    print("Generating synthetic AIS...")

    df, ground_truth = generate_scenario_dataset(
        config
    )

    if df is None:
        raise RuntimeError(
            "generate_scenario_dataset() returned no dataframe."
        )

    if ground_truth is None:
        raise RuntimeError(
            "generate_scenario_dataset() returned no ground truth."
        )

    print(
        f"Generated AIS records: "
        f"{len(df):,}"
    )

    # ============================================================
    # 11. CREATE OUTPUT DIRECTORY
    # ============================================================

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    # ============================================================
    # 12. OUTPUT FILES
    # ============================================================

    ais_path = (
        OUTPUT_DIR
        / "synthetic_scenario_005.csv"
    )

    ground_truth_path = (
        OUTPUT_DIR
        / "synthetic_scenario_005_ground_truth.json"
    )

    # ============================================================
    # 13. SAVE AIS
    # ============================================================

    df.to_csv(
        ais_path,
        index=False,
    )

    # ============================================================
    # 14. AUGMENT GROUND TRUTH
    #
    # Preserve the generator's ground truth and add explicit
    # forward-drift provenance.
    # ============================================================

    if isinstance(ground_truth, dict):

        ground_truth["forward_drift_validation"] = {
            "generated_by": "DriftEngine.forward_drift",
            "windage": WINDAGE,
            "duration_hours": DRIFT_DURATION_HOURS,
            "timestep_minutes": TIMESTEP_MINUTES,
            "true_release_lat": TRUE_SOURCE_LATITUDE,
            "true_release_lon": TRUE_SOURCE_LONGITUDE,
            "true_release_time": (
                RELEASE_TIME.isoformat()
            ),
            "generated_observation_lat": observation_lat,
            "generated_observation_lon": observation_lon,
            "generated_observation_time": (
                observation_time.isoformat()
            ),
        }

    # ============================================================
    # 15. SAVE GROUND TRUTH
    # ============================================================

    with ground_truth_path.open(
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            ground_truth,
            f,
            indent=2,
            default=str,
        )

    # ============================================================
    # 16. FINAL REPORT
    # ============================================================

    print()
    print("=" * 80)
    print("SCENARIO-005 GENERATED SUCCESSFULLY")
    print("=" * 80)

    print()
    print("TRUE SOURCE")
    print(
        f"  Vessel     : "
        f"{config.source_vessel_id}"
    )

    print(
        f"  Position   : "
        f"{config.release_lat:.6f}, "
        f"{config.release_lon:.6f}"
    )

    print(
        f"  Release    : "
        f"{config.release_time.isoformat()}"
    )

    print()
    print("GENERATED OBSERVATION")
    print(
        f"  Position   : "
        f"{observation_lat:.8f}, "
        f"{observation_lon:.8f}"
    )

    print(
        f"  Time       : "
        f"{observation_time.isoformat()}"
    )

    print()
    print("DATASET")
    print(
        f"  AIS records: "
        f"{len(df):,}"
    )

    print(
        f"  Background : "
        f"{config.num_background_vessels}"
    )

    print(
        f"  Decoys     : "
        f"{config.num_decoy_vessels}"
    )

    print()
    print("FILES")
    print(
        f"  AIS         : "
        f"{ais_path}"
    )

    print(
        f"  Ground truth: "
        f"{ground_truth_path}"
    )

    print()
    print("=" * 80)
    print("NEXT STEP: INGEST SCENARIO-005")
    print("=" * 80)


if __name__ == "__main__":
    main()